version: '3.7'

services:
  app:
    build:
      context: .
    depends_on:
      - redis
    ports:
      - '80:80'
    environment:
      - REDIS_URL=redis://redis
    entrypoint: ["make", "app"]

  worker:
    build:
      context: .
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis
    entrypoint: ["make", "worker"]

  redis:
    image: 'redis:6'